### ISSUE TITLE
Checking a diff throws a missing file exception if HEAD doesn't contain a file in the diff

### ISSUE THREAD

**Issue by djkgamc** [lintrule/lintrule#11]
I tried diffing specific commits, such as: 
rules check --diff bb9fb02818fd154c101047a71899deef6c953586...5f3b4b91662b094bf994fc86466b9814a2861dd2

and received this error:
Uncaught (in promise) NotFound: No such file or directory (os error 2): readfile '__tests__/resolvers.test.ts

It's checking my current file structure for files, but it shouldn't be, it should just be paying attention to the specified diff.

**Comment by Flaque** [comment]
Thank you for finding this! Will take a look

**Comment by Flaque** [comment]
This should be fixed now! Please run `rules upgrade`!
