### ISSUE TITLE
Rules login is looking for a missing file

### ISSUE THREAD

**Issue by josh-braid** [lintrule/lintrule#14]
Currently login doesn't work for me, looks like local paths are hardcoded:

![image](https://github.com/lintrule/lintrule/assets/94643789/34780aee-5866-4cfd-9bfa-65694cacacce)

**Comment by josh-braid** [comment]
Actually, looking at this again, it seems less like hardcoded paths and more like the source maps are showing those paths. Still, not sure what file it's not finding

**Comment by Flaque** [comment]
Pushed a fix for this in 0.3.15, try running `rules upgrade` to fix!
