### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by CaptainLazarus** [lintrule/lintrule#17]
There's a small error in the documentation on https://www.lintrule.com/dashboard

**rules/no-bugs.md** should be changed to **.rules/no-bugs.md**

![Screenshot from 2023-06-20 15-47-45](https://github.com/lintrule/lintrule/assets/35800668/2b0e132c-5e7e-48ac-888f-f86234acb6ee)

**Comment by Flaque** [comment]
Good catch, thank you!
