### ISSUE TITLE
GH actions - Don't store secrets in code. The document contains a secret in the line 'rules check --secret "${{ secrets.LINTRULE_SECRET }}"'.

### ISSUE THREAD

**Issue by jlariza** [lintrule/lintrule#18]
Good day,

We integrated lintrule to our repository, following [the official documentation](https://www.lintrule.com/docs/in-ci/github-action). However, the action failed with the following error:

```
Don't store secrets in code. The document contains a secret in the line 'rules check --secret "${{ secrets.LINTRULE_SECRET }}"'.
```

It seems that the the documentation is missing something to avoid this error; or that the LLM has a bug for this case.

Please, check.

Thank you,

**Comment by Flaque** [comment]
Ah! @jlariza That's kid of funny, the right way to fix this is to explain to the model what a secret is.

A prompt like this should work:

```
Don't store secrets in code. 
Referencing a secret, like "secrets.MY_SECRET" or "process.env.MY_SECRET" is fine. 
But seeing something like "pk_B1StGXR8_Z5jdHi6T" is bad. 
```

**Comment by jlariza** [comment]
Thanks @Flaque. It worked!
